-- Configuration-driven examples. Replace FactCCMRStatus with calculated status table if materialized.
CTE Students Count = /* CTE Students Count: filter by named pathway/status/flag as documented */ DISTINCTCOUNT(DimStudent[LocalStudentID])
Level 1 Completed Count = /* Level 1 Completed Count: filter by named pathway/status/flag as documented */ DISTINCTCOUNT(DimStudent[LocalStudentID])
Level 2 Completed Count = /* Level 2 Completed Count: filter by named pathway/status/flag as documented */ DISTINCTCOUNT(DimStudent[LocalStudentID])
Level 3 Completed Count = /* Level 3 Completed Count: filter by named pathway/status/flag as documented */ DISTINCTCOUNT(DimStudent[LocalStudentID])
Level 4 Completed Count = /* Level 4 Completed Count: filter by named pathway/status/flag as documented */ DISTINCTCOUNT(DimStudent[LocalStudentID])
Concentrator Count = /* Concentrator Count: filter by named pathway/status/flag as documented */ DISTINCTCOUNT(DimStudent[LocalStudentID])
Completer Count = /* Completer Count: filter by named pathway/status/flag as documented */ DISTINCTCOUNT(DimStudent[LocalStudentID])
Missing Next CTE Course Count = /* Missing Next CTE Course Count: filter by named pathway/status/flag as documented */ DISTINCTCOUNT(DimStudent[LocalStudentID])
IBC Attempted Count = /* IBC Attempted Count: filter by named pathway/status/flag as documented */ DISTINCTCOUNT(DimStudent[LocalStudentID])
IBC Passed Count = /* IBC Passed Count: filter by named pathway/status/flag as documented */ DISTINCTCOUNT(DimStudent[LocalStudentID])
IBC Verified Count = /* IBC Verified Count: filter by named pathway/status/flag as documented */ DISTINCTCOUNT(DimStudent[LocalStudentID])
IBC Not Aligned Count = /* IBC Not Aligned Count: filter by named pathway/status/flag as documented */ DISTINCTCOUNT(DimStudent[LocalStudentID])
CTE One Course Away Count = /* CTE One Course Away Count: filter by named pathway/status/flag as documented */ DISTINCTCOUNT(DimStudent[LocalStudentID])
